

services:
  backend:
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: npm run dev
    environment:
      - NODE_ENV=development
